# Example Site settings

google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md
  - about.md
  - contact.md

footer: 'add me on <a href="https://www.linkedin.com/in/jamila-reed-07b043144/">linkedin</a>'

style: dark
listen_for_clients_preferred_style: true 

plugins:
  - jekyll-seo-tag
